upload_max_filesize = 0
post_max_size = 0
max_execution_time = 0
max_input_time = -1
memory_limit = 512M

session.gc_maxlifetime = 14400
session.gc_probability = 1
session.gc_divisor = 100
session.use_strict_mode = 1
session.sid_length = 48
session.sid_bits_per_character = 6
